@eventsimulator = https://localhost:7242

### MIGRATE
# @timeout 10000 m
POST {{eventsimulator}}/api/migrate
Content-Type: application/json

{
    "From": "2024-01-01",
    "To": "2024-01-01",
    "Organizations": ["ttd"],
    "Force": true
}

###

//{
//  "From": "2024-01-01",
//  "To": "2024-01-01",
//  "Organizations": ["digdir"],
//  "Force": true
//}

### SINGLE INSTANCE MIGRATE
POST {{eventsimulator}}/api/migrate
Content-Type: application/json

{
    "Instances": [
        "50055202/e40b03b2-3108-470d-92fb-7d06ae4ab10a"
    ]
}

### DELETE
DELETE {{eventsimulator}}/api/table/truncate
Content-Type: application/json
