@AdapterHost = https://localhost:7241
@DialogportenHost = https://altinn-dev-api.azure-api.net/dialogporten

### Authorize
GET https://altinn-testtools-token-generator.azurewebsites.net/api/GetEnterpriseToken
    ?env=tt02
    &org=digdir
    &orgNo=991825827
    &scopes=digdir:dialogporten.serviceprovider digdir:dialogporten.serviceprovider.search digdir:dialogporten digdir:dialogporten.developer.test
    &ttl=86400
Authorization: Basic {{testTokenGeneratorUsername}} {{testTokenGeneratorPassword}}

> {%
    client.global.set("auth_token", response.body)
%}

### Get dialog
GET {{DialogportenHost}}/api/v1/serviceowner/dialogs/019368e0-71f5-72fc-a1d8-3bb85540b14e
Authorization: Bearer {{auth_token}}

### Purge dialog
POST {{DialogportenHost}}/api/v1/serviceowner/dialogs/019368e0-71f5-72fc-a1d8-3bb85540b14e/actions/purge
Authorization: Bearer {{auth_token}}

### Sync
POST {{AdapterHost}}/syncDialog
Content-Type: application/json

{
   "PartyId": "50892513",
   "InstanceId": "434fe9b5-0605-4b27-a9a7-1c0750e78e02"
}

