@AdapterHost = https://localhost:7211
@DialogportenHost = https://altinn-dev-api.azure-api.net/dialogporten

### Sync
POST {{AdapterHost}}/syncDialog
Content-Type: application/json

{
   "PartyId": "50126876",
   "InstanceId": "7eac5837-ce4c-42fc-a1d8-3bb85540b14e"
}

### Check
GET {{DialogportenHost}}/api/v1/serviceowner/dialogs/019368e0-71f5-72fc-a1d8-3bb85540b14e

