@baseUri = https://localhost:7241
@instanceId = 51583478/4f230136-d9b2-40a8-9c53-22fbc8b9ef26

### Log into maskinporten
// @no-log
GET  https://altinn-testtools-token-generator.azurewebsites.net/api/GetEnterpriseToken?org=digdir&env={{env}}&scopes=altinn:storage/instances.syncadapter&ttl=86400
Authorization: Basic {{username}} {{password}}

> {% client.global.set("maskinportenToken", response.body) %}

### Get instance data
// @no-log
GET {{altinnPlatformBaseUri}}/storage/api/v1/instances/{{instanceId}}
Authorization: Bearer {{maskinportenToken}}

> {% 
    const idParts = response.body.id.split('/');
    client.global.set("syncDialogDto", JSON.stringify({
        "appId": response.body.appId,
        "partyId": idParts[0],
        "instanceId": idParts[1],
        "instanceCreatedAt": response.body.created,
        "isMigration": true
    }))
 %}

### Resume
// @no-log
POST {{baseUri}}/api/v1/syncDialog
Content-Type: application/json

{{syncDialogDto}}