@instanceId = 50055202/5f88eab6-68b5-4c7a-8cc0-4fd797b05e11

### Log into maskinporten
// @no-log
GET  https://altinn-testtools-token-generator.azurewebsites.net/api/GetEnterpriseToken?org=digdir&env={{env}}&scopes=altinn:storage/instances.syncadapter&ttl=86400
Authorization: Basic {{username}} {{password}}

> {% client.global.set("maskinportenToken", response.body) %}

### Get instance data
// @no-log
GET {{altinnPlatformBaseUri}}/storage/api/v1/instances/{{instanceId}}
Authorization: Bearer {{maskinportenToken}}

> {%
    const idParts = response.body.id.split('/');
    client.global.set("syncDialogDto", JSON.stringify({
        "appId": response.body.appId,
        "partyId": idParts[0],
        "instanceId": idParts[1],
        "instanceCreatedAt": response.body.created,
        "isMigration": true
    }))
 %}

### Sync
// @no-log
POST {{baseUri}}/api/v1/syncDialog
Authorization: Bearer {{maskinportenToken}}
Content-Type: application/json

{{syncDialogDto}}